# config.example.py
import os

WEB_USERNAME = "admin"
WEB_PASSWORD = "CHANGE_ME"
SECRET_KEY = "CHANGE_ME" 

RUNPOD_API_KEY = os.environ.get("RUNPOD_API_KEY", "YOUR_RUNPOD_API_KEY")
RUNPOD_SSH_PRIVATE_KEY_PATH = os.path.expanduser(
    os.environ.get("RUNPOD_SSH_PRIVATE_KEY_PATH", "~/.ssh/id_ed25519")
)
RUNPOD_CLOUD_TYPE = os.environ.get("RUNPOD_CLOUD_TYPE", "COMMUNITY")
RUNPOD_DATA_CENTER_IDS = ["EU-RO-1"]
RUNPOD_MAX_RUNTIME_MIN = 180 

RUNPOD_VOLUME_DATACENTER = "EU-RO-1"
RUNPOD_VOLUME_SIZE_GB = 50
RUNPOD_S3_ENDPOINT = "https://s3api-eu-ro-1.runpod.io"
RUNPOD_S3_ACCESS_KEY = "YOUR_S3_ACCESS_KEY"
RUNPOD_S3_SECRET_KEY = "YOUR_S3_SECRET_KEY"